# Generated by Django 4.1.3 on 2023-02-23 15:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('marks', models.IntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            managers=[
                ('student', django.db.models.manager.Manager()),
            ],
        ),
    ]
